apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: flower-addon-config
  namespace: open-cluster-management
spec:
  customizedVariables:
    - name: SuperLinkAddress
      value: "superlink.flower-system.svc.cluster.local"
    - name: SuperLinkPort
      value: "9092"
    - name: Image
      value: "flwr/supernode:1.15.0"
    - name: ImagePullPolicy
      value: "IfNotPresent"
