apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: flower-addon
spec:
  installStrategy:
    type: Placements
    placements:
      - name: flower-addon-gpu-placement
        namespace: open-cluster-management
        configs:
          - group: addon.open-cluster-management.io
            resource: addondeploymentconfigs
            name: flower-addon-config
            namespace: open-cluster-management
