apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-cluster-management
resources:
  - ../../../supernode
  - placement.yaml
  - managedclustersetbinding.yaml
patches:
  - path: clustermanagementaddon-patch.yaml
    target:
      kind: ClusterManagementAddOn
      name: flower-addon
