apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-cluster-management
resources:
  - addon-template.yaml
  - addon-deployment-config.yaml
  - placement.yaml
  - managedclustersetbinding.yaml
  - clustermanagementaddon.yaml
