apiVersion: v1
kind: Service
metadata:
  name: supernode-1
  namespace: flower
  labels:
    app.kubernetes.io/name: supernode
    app.kubernetes.io/instance: supernode-1
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: supernode
    app.kubernetes.io/instance: supernode-1
  ports:
    - name: clientappio
      port: 9094
      targetPort: 9094
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: supernode-2
  namespace: flower
  labels:
    app.kubernetes.io/name: supernode
    app.kubernetes.io/instance: supernode-2
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: supernode
    app.kubernetes.io/instance: supernode-2
  ports:
    - name: clientappio
      port: 9095
      targetPort: 9095
      protocol: TCP
