{{- if .Values.superlink.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: superlink
  namespace: {{ .Values.superlink.namespace }}
  labels:
    {{- include "flower-addon.superlinkLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superlink
  namespace: {{ .Values.superlink.namespace }}
  labels:
    {{- include "flower-addon.superlinkLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "flower-addon.superlinkSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flower-addon.superlinkSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: superlink
      containers:
      - name: superlink
        image: {{ .Values.superlink.image.repository }}:{{ .Values.superlink.image.tag }}
        imagePullPolicy: {{ .Values.superlink.image.pullPolicy }}
        args:
        {{- range .Values.superlink.args }}
        - {{ . | quote }}
        {{- end }}
        ports:
        - name: exec
          containerPort: 9091
          protocol: TCP
        - name: fleet
          containerPort: 9092
          protocol: TCP
        - name: control
          containerPort: 9093
          protocol: TCP
        resources:
          {{- toYaml .Values.superlink.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }}
